config/routes.rb
Rails.application.routes.draw do
  resources :courses
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'home#index'
  match '/course_outline' => "courses#index", via: ['get']
  match '/our_team' => "team#index", via: ['get']
  match '/interactions' => "interactions#index", via: ['get']
  match '/contact_us' => "contact#index", via: ['get']
  match '/fibonacci_and_factorial' => "computations#index", via: ['get']
  match '/fibonacci_and_factorial_computation' => "computations#fibonacci_and_factorial", via: ['post']
  match '/tower_of_hanoi' => "computations#index_hanoi", via: ['get']
  match '/tower_of_hanoi_computation' => "computations#tower_of_hanoi", via: ['post']
  match '/sorting' => "sorting#index", via: ['get']
  match '/sorted' => "sorting#sorted", via: ['post']
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  paginates_per 5
end

app/controllers/about_controller.rb
class AboutController < ApplicationController

  def index
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/computations_controller.rb
class ComputationsController < ApplicationController
  skip_before_action :verify_authenticity_token
  include Computations

  def index
  end

  def index_hanoi
  end

  def fibonacci_and_factorial
    #method to execute the fibonacci  and factorial functions
    @method = params[:method]
    @number = (params[:number]).to_i
    if @method == "Fibonacci"
      @result = fibonacci_computation(@number)
    end
    if @method == "Factorial"
      @result = factorial_computation(@number)
    end
  end
end

app/controllers/concerns/computations.rb
module Computations
  def fibonacci_computation(number)
    return number if(0..1).include? number
    (fibonacci_computation(number - 1) + fibonacci_computation(number - 2))
  end

  def factorial_computation(number)
    #(Math.gamma(number + 1)).to_i
    (1..number).inject(:*)
  end

  def bubble_sort(array)
    return array if array.size <= 1
    swap = true
      while swap
        swap = false
        (array.length - 1).times do |x|
          if array[x] > array[x+1]
            array[x], array[x+1] = array[x+1], array[x]
            swap = true
          end
        end
      end
    array
  end

  def insertion_sort(array)
    (array.length).times do |j|
      while j > 0
        if array[j-1] > array[j]
          array[j], array[j-1] = array[j-1], array[j]
        else
          break
        end
        j-=1
      end
    end
    array
  end

  def selection_sort(array)
    n = array.length - 1
    n.times do |i|
      min_index = i
      for j in (i + 1)..n
        min_index = j if array[j] < array[min_index]
      end
      array[i], array[min_index] = array[min_index], array[i] if min_index != i
    end
    array
  end
    def merge_sort(array)
      if array.length <= 1
        array
      else
        mid = (array.length / 2).floor
        left = merge_sort(array[0..mid-1])
        right = merge_sort(array[mid..array.length])
        merge(left, right)
      end
    end

    def merge(left, right)
      if left.empty?
        right
      elsif right.empty?
        left
      elsif left[0] < right[0]
        [left[0]] + merge(left[1..left.length], right)
      else
        [right[0]] + merge(left, right[1..right.length])
      end
    end

    def quick_sort(array)
      return array if array.length <= 1
      pivot = array.delete_at(rand(array.length))

      left = Array.new
      right = Array.new

      array.each do |x|
        if x <= pivot
          left << x
        else
          right << x
        end
      end

      return *quick_sort(left), pivot ,*quick_sort(right)

  end
end

app/controllers/concerns/stack.rb
class Stack
  class Node
    attr_accessor :next, :data
    def initialize data
        self.data = data
        self.next = nil
    end
  end

  attr_accessor :head, :tail, :length

  def initialize
    self.head = nil
    self.length = 0
  end

  def push data
    node = Node.new data
    if length == 0
      self.tail = node
    end

    node.next = self.head
    self.head = node
    self.length += 1
  end

  def pop
    return nil unless self.length > 0

    self.head = self.head.next
    self.tail = nil if self.length == 1
    self.length -= 1
  end

  def peek
    self.head
  end

  def clear
    while self.peek
      pop
    end
  end

  def each
    return nil unless block_given?
    current = self.head
    while current
        yield current
        current = current.next
    end
  end

  def print
    if self.length == 0
        puts "empty"
    else
        self.each { |node| puts node.data }
    end
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

  def index
  end
  
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show]

  def index
    @courses = Course.all.page params[:page]
  end

  def show
  end

  private
  def set_course
    @course = Course.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
end

app/controllers/interactions_controller.rb
class InteractionsController < ApplicationController
  require "stack"
  require "queue"

  def index
    @console = console
  end

end

app/controllers/sorting_controller.rb
class SortingController < ApplicationController
  skip_before_action :verify_authenticity_token
  include Computations
  def index
  end

  def sorted
    @arr = []
    @unsorted = []
    @method = params[:sort_method]
    number = (params[:number]).to_i
    for i in 1..number
      i = rand(1000)
      @arr << i
      @unsorted << i
    end
    if @method == "Bubble sort"
      @result = bubble_sort(@arr)
    elsif @method == "Insertion sort"
      @result = insertion_sort(@arr)
    elsif @method == "Selection sort"
      @result = selection_sort(@arr)
    elsif @method == "Quick sort"
      @result = quick_sort(@arr)
    elsif @method == "Merge sort"
      @result = merge_sort(@arr)
    else
      @arr = []
      @unsorted = []
    end
  end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController

  def index
  end
  
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/computations_helper.rb
module ComputationsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/interactions_helper.rb
module InteractionsHelper
end

app/helpers/sorting_helper.rb
module SortingHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/views/computations/fibonacci_and_factorial.html.erb
<%= provide(:title, 'Fibonacci & Factorial') %>
<section class="bg-light-gray">
    <div class="container">
      <% if @method == "Fibonacci"%>
        <div class="row">
            <div class="col-lg-6 col-md-12 sm-margin-20px-bottom margin-twenty-five-left">
                <div class="services-block padding-45px-tb padding-25px-lr sm-padding-35px-tb sm-padding-20px-lr xs-padding-30px-tb xs-padding-15px-lr last-paragraph-no-margin wow fadeInUp">
                    <div class="text-extra-dark-gray text-uppercase text-small font-weight-600 alt-font margin-5px-bottom">Result for <%=@number%> Fibonacci</div>
                    <p class="center-col">Result is <%= @result %></p>
                </div>
            </div>
        </div>
      <% end %>
      <% if @method == "Factorial"%>
        <div class="row">
            <div class="col-lg-6 col-md-12 sm-margin-20px-bottom margin-twenty-five-left">
                <div class="services-block padding-45px-tb padding-25px-lr sm-padding-35px-tb sm-padding-20px-lr xs-padding-30px-tb xs-padding-15px-lr last-paragraph-no-margin wow fadeInUp">
                    <div class="text-extra-dark-gray text-uppercase text-small font-weight-600 alt-font margin-5px-bottom">Result for <%=@number%> Factorial</div>
                    <p class="center-col">Result is <%= @result %></p>
                </div>
            </div>
        </div>
      <% end %>
    </div>
</section>

app/views/computations/index.html.erb
<%= provide(:title, 'Fibonacci and Factorial') %>
<section>
    <div class="container" align="center">
      <h5>Fibonacci & Factorial</h5>
      <div class="row">
        <div class="col-lg-6 col-md-12 sm-margin-20px-bottom margin-twenty-five-left">
          <%= form_tag(fibonacci_and_factorial_computation_path, :method => "post", remote: true) do %>
            <%= select_tag :method, options_for_select(["select option", "Fibonacci", "Factorial"])%>
            <%= number_field_tag :number, params[:number], placeholder: "Enter number to compute", required: true %>
            <%= submit_tag "Compute",class: 'btn btn-primary', :name => nil %>
          <% end %>
        </div>
      </div>
    </div>
</section>

app/views/computations/index_hanoi.html.erb
<%= provide(:title, 'Hanoi') %>
<head>
  <style>

   #container { position:absolute; top:150px; left:150px; border:1px solid black; height:350px; width:760px; }

   #bar0 { position:absolute; top:100px; left:130px; height:200px; width:30px; }

   #bar1 { position:absolute; top:100px; left:360px; height:200px; width:30px; }

   #bar2 { position:absolute; top:100px; left:600px; height:200px; width:30px; }

   .disk { padding:0; margin:0; position:absolute; border:1px solid gray; height:26px;
           -moz-box-sizing:border-box; box-sizing:border-box; border-radius:4px;}

   /* left of disk0 at 35px; left = 130 (bar0 left) -w/2 + 15 (bar width/2)  */
   #disk0  { top:274px; left:35px;background:#DDEEFE; width:220px;  }
   #disk1 { top:248px; left:55px;background:#CEEDDF; width:180px; }
   #disk2 { top:222px; left:75px;background:#FEEEEF; width:140px; }
   #disk3 { top:196px; left:95px;background:#EEFEFF; width:100px; }
   #disk4 { top:170px; left:115px;background:#EEFECC; width:60px;  }

   #bottombar { position:absolute; top:300px; left:10px;background:#222; border:1px solid black; height:30px; width:740px; }

   label { float:right; width:100px; margin-top:8px}

   button { float:right; }

   img { height:200px; width:30px; padding:0; margin:0; } /* for towers (bars) */

  .insideImg { z-index:100; position:absolute; border:0;top:-1px; height:14px; width:30px; }
  </style>
</head>
<section class="team bg-light-gray">
  <div class="container">

  <div id="bar0"><%= image_tag('Bar.png')%></div>

  <div id="bar1"><%= image_tag('Bar.png')%></div>

  <div id="bar2"><%= image_tag('Bar.png')%></div>
  <div id="bottombar"></div>

  <div class="disk" id="disk0" ><%= image_tag('Bar2.png', :class=>"insideImg", :style=>"left:94px")%></div>
  <div class="disk" id="disk1" ><%= image_tag('Bar2.png', :class=>"insideImg", :style=>"left:74px")%></div>
  <div class="disk" id="disk2" ><%= image_tag('Bar2.png', :class=>"insideImg", :style=>"left:54px")%></div>
  <div class="disk" id="disk3" ><%= image_tag('Bar2.png', :class=>"insideImg", :style=>"left:34px")%></div>
  <div class="disk" id="disk4" ><%= image_tag('Bar2.png', :class=>"insideImg", :style=>"left:14px")%></div>
  <button onclick="executeHanoi()" class="btn btn-primary" >Start</button>

  <label>Speed <select id="speedSelectList" >
  <option  value="1" >fast</option>
  <option  value="10" >medium</option>
  <option  value="20" >slow</option>
  </select>
  </label>

  <label>No. of Disks<select id="diskSelectList" >
  <option  value="5" >5 disks</option>
  <option  value="4" >4 disks</option>
  <option  value="3" >3 disks</option>
  </select>
  </label>
  </div>
</section>

<script type="text/javascript" >
    "use strict";
    var myTimer = null;
    var moveInfo;
    var moveInc = 1;
    var speed;

    var callStack;

    var barsInfo = [{}, {}, {}, {}, {}];

    var diskPosTop, diskPosLeft, DiskID;

    window.onload = function ()
    {   diskPosTop = new Array();
        diskPosLeft = new Array();
        DiskID = [disk0, disk1, disk2, disk3, disk4]
        for (var i = 0; i < 5; i++)
        {  diskPosTop[i] = DiskID[i].style.top;
           diskPosLeft[i] = DiskID[i].style.left; }

    }

    function executeHanoi()
     {
        var speed = parseInt(speedSelectList.options[speedSelectList.selectedIndex].value);
        var  diskCount = parseInt(diskSelectList.options[diskSelectList.selectedIndex].value);
        // alert(diskCount);
        // var diskCount =3;

        // Move Disks to start column
        for (var i = 0; i < 5; i++)
        {  DiskID[i].style.top = diskPosTop[i];
           DiskID[i].style.left= diskPosLeft[i];
        }

        barsInfo[0].disks = ['disk0', 'disk1', 'disk2', 'disk3', 'disk4'];
        //alert(barsInfo[0].disks.pop().id);
        barsInfo[1].disks = [];
        barsInfo[2].disks = [];
        barsInfo[3].disks = [];
        barsInfo[4].disks = [];

        switch (diskCount) {
            case 3: barsInfo[0].disks.pop(); barsInfo[0].disks.pop();
                disk3.style.display = "none"; disk4.style.display = "none"; break;

            case 4: barsInfo[0].disks.pop();
                disk4.style.display = "none"; break;
        }

        callStack = [];  // callStack array is global

        Hanoi(diskCount, 0, 2, 1);

        moveDisk(); // moveDisk takes its parameters from callStack
    }


    function Hanoi(n, from, to, via) {
        if (n == 0) return;

        Hanoi(n - 1, from, via, to);
        // moveDisk(from,to);

        callStack.push([from, to]); // save parameters to callStack array
        Hanoi(n - 1, via, to, from);

    }


    function moveDisk() {
        if (callStack.length == 0) return;

        var param = callStack.shift();  // Get call parameters from callStack
        // Note: throughout the code, I use fromBar, toBar to refer to towers
        var  fromBar = param[0];
        var toBar = param[1];

        var elem = document.getElementById(barsInfo[fromBar].disks.pop());  // find top elemnet in fromBar

        moveInfo = { elem: elem,
            fromBar: fromBar,
            toBar: toBar,
            whichPos: "top", // element position property for movement
            dir: -1,  // 1 or -1
            state: "up", // move upward
            endPos: 60    // end position (in pixels) for move upward
        }

        myTimer = setInterval(animateMove, speed); // Start animation
    }

    function animateMove() {
        var elem = moveInfo.elem;
        var dir = moveInfo.dir;

        var pos = parseInt(elem[(moveInfo.whichPos == "left") ? "offsetLeft" : "offsetTop"]);

        if (((dir == 1) && (pos >= moveInfo.endPos)) || ((dir == -1) && (pos <= moveInfo.endPos))) {  // alert(moveInfo.state);
            if (moveInfo.state == "up") {
                moveInfo.state = "hor";
                moveInfo.whichPos = "left";
                moveInfo.dir = 1;
                if (moveInfo.fromBar > moveInfo.toBar) moveInfo.dir = -1;
                //alert("toBar:" + moveInfo.toBar);
                var toBar = document.getElementById("bar" + moveInfo.toBar);
                // Next line: 15px is half of tower width
                moveInfo.endPos = toBar.offsetLeft - Math.floor(elem.offsetWidth / 2) + 15;
                return;
            }

            else if (moveInfo.state == "hor") // move down
            {
                moveInfo.state = "down";
                moveInfo.whichPos = "top";
                moveInfo.dir = 1;
                //alert(elem.offsetHeight);
                moveInfo.endPos = document.getElementById("bottombar").offsetTop - (barsInfo[moveInfo.toBar].disks.length + 1) * elem.offsetHeight;
                return;
            }

            else // end of current call to moveDisk, issue next call
            {
                clearInterval(myTimer);  // cancel timer
                barsInfo[moveInfo.toBar].disks.push(elem.id);
                moveDisk();
                return;
            }
        }


        // Move Disk
        pos = pos + dir * moveInc;
        elem.style[moveInfo.whichPos] = pos + "px";

        // Move the inside middle image
        if (moveInfo.state == "up") {
            var fromBar = document.getElementById("bar" + moveInfo.fromBar);
            if (elem.offsetTop < fromBar.offsetTop) {
                var x = elem.getElementsByClassName("insideImg")[0].offsetHeight;
                if (x > 0) elem.getElementsByClassName("insideImg")[0].style.height = x - moveInc + "px";
            }
        }

        if (moveInfo.state == "down") {
            var toBar = document.getElementById("bar" + moveInfo.toBar);
            if (elem.offsetTop > toBar.offsetTop) {
                var x = elem.getElementsByClassName("insideImg")[0].offsetHeight;
                if (x < 14) elem.getElementsByClassName("insideImg")[0].style.height = x + moveInc + "px";
            }
        }

    }

</script>