config/routes.rb
Rails.application.routes.draw do
  resources :courses
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'home#index'
  match '/course_outline' => "courses#index", via: ['get']
  match '/our_team' => "team#index", via: ['get']
  match '/interactions' => "interactions#index", via: ['get']
  match '/contact_us' => "contact#index", via: ['get']
  match '/fibonacci_and_factorial' => "computations#index", via: ['get']
  match '/fibonacci_and_factorial_computation' => "computations#fibonacci_and_factorial", via: ['post']
  match '/tower_of_hanoi' => "computations#index_hanoi", via: ['get']
  match '/tower_of_hanoi_computation' => "computations#tower_of_hanoi", via: ['post']
  match '/sorting' => "sorting#index", via: ['get']
  match '/sorted' => "sorting#sorted", via: ['post']
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  paginates_per 5
end

app/controllers/about_controller.rb
class AboutController < ApplicationController

  def index
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/computations_controller.rb
class ComputationsController < ApplicationController
  skip_before_action :verify_authenticity_token
  include Computations

  def index
  end

  def index_hanoi
  end

  def fibonacci_and_factorial
    #method to execute the fibonacci  and factorial functions
    @method = params[:method]
    @number = (params[:number]).to_i
    if @method == "Fibonacci"
      @result = fibonacci_computation(@number)
    end
    if @method == "Factorial"
      @result = factorial_computation(@number)
    end
  end
end

app/controllers/concerns/stack.rb
class Stack
  class Node
    attr_accessor :next, :data
    def initialize data
        self.data = data
        self.next = nil
    end
  end

  attr_accessor :head, :tail, :length

  def initialize
    self.head = nil
    self.length = 0
  end

  def push data
    node = Node.new data
    if length == 0
      self.tail = node
    end

    node.next = self.head
    self.head = node
    self.length += 1
  end

  def pop
    return nil unless self.length > 0

    self.head = self.head.next
    self.tail = nil if self.length == 1
    self.length -= 1
  end

  def peek
    self.head
  end

  def clear
    while self.peek
      pop
    end
  end

  def each
    return nil unless block_given?
    current = self.head
    while current
        yield current
        current = current.next
    end
  end

  def print
    if self.length == 0
        puts "empty"
    else
        self.each { |node| puts node.data }
    end
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

  def index
  end
  
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show]

  def index
    @courses = Course.all.page params[:page]
  end

  def show
  end

  private
  def set_course
    @course = Course.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
end

app/controllers/interactions_controller.rb
class InteractionsController < ApplicationController
  require "stack"
  require "queue"

  def index
    @console = console
  end

end

app/controllers/sorting_controller.rb
class SortingController < ApplicationController
  skip_before_action :verify_authenticity_token
  include Computations
  def index
  end

  def sorted
    @arr = []
    @unsorted = []
    @method = params[:sort_method]
    number = (params[:number]).to_i
    for i in 1..number
      i = rand(1000)
      @arr << i
      @unsorted << i
    end
    if @method == "Bubble sort"
      @result = bubble_sort(@arr)
    elsif @method == "Insertion sort"
      @result = insertion_sort(@arr)
    elsif @method == "Selection sort"
      @result = selection_sort(@arr)
    elsif @method == "Quick sort"
      @result = quick_sort(@arr)
    elsif @method == "Merge sort"
      @result = merge_sort(@arr)
    else
      @arr = []
      @unsorted = []
    end
  end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController

  def index
  end
  
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/computations_helper.rb
module ComputationsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/interactions_helper.rb
module InteractionsHelper
end

app/helpers/sorting_helper.rb
module SortingHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/views/contact/index.html.erb
<%= provide(:title, 'Contact Us') %>
<!-- start page title section -->
<section class="page-title-section bg-img cover-background theme-overlay" data-overlay-dark="7" data-background="<%= image_tag("bg9.jpg") %>">
    <div class="container">

        <div class="row">
            <div class="col-md-12">
                <h1>Contact Us</h1>
            </div>
            <div class="col-md-12">
                <ul>
                    <li><a href="<%= root_path %>">Home</a></li>
                    <li><a href="javascript:void(0)">Contact Us</a></li>
                </ul>
            </div>
        </div>

    </div>
</section>
<!-- end page title section -->

<!-- start contact info section -->
<section class="bg-light-gray">
    <div class="container">

        <div class="row">
            <div class="col-lg-4 col-md-12 sm-margin-20px-bottom">
                <div class="services-block padding-45px-tb padding-25px-lr sm-padding-35px-tb sm-padding-20px-lr xs-padding-30px-tb xs-padding-15px-lr last-paragraph-no-margin wow fadeInUp">
                    <div class="title-box margin-25px-bottom sm-margin-15px-bottom">
                        <i class="fas fa-map-marker-alt text-theme-color"></i>
                        <div class="box-circle-large"></div>
                        <div class="box-circle-small"></div>
                    </div>
                    <div class="text-extra-dark-gray text-uppercase text-small font-weight-600 alt-font margin-5px-bottom">Visit Our Office</div>
                    <p class="center-col">MAKERERE UNIVERSITY,COCIS,COMPUTER SCIENCE
                        <br>New York, NY 10013.</p>
                </div>
            </div>
            <div class="col-lg-4 col-md-12 sm-margin-20px-bottom wow fadeInUp" data-wow-delay="0.2s">
                <div class="services-block padding-45px-tb padding-25px-lr sm-padding-35px-tb sm-padding-20px-lr xs-padding-30px-tb xs-padding-15px-lr last-paragraph-no-margin">
                    <div class="title-box margin-25px-bottom sm-margin-15px-bottom">
                        <i class="fas fa-comments text-theme-color"></i>
                        <div class="box-circle-large"></div>
                        <div class="box-circle-small"></div>
                    </div>
                    <div class="text-extra-dark-gray text-uppercase text-small font-weight-600 alt-font margin-5px-bottom">Let's Talk</div>
                    <p class="center-col">Phone: (+256)779467316
                        <br>Fax: 123 456 789</p>
                </div>
            </div>
            <div class="col-lg-4 col-md-12 wow fadeInUp" data-wow-delay="0.4s">
                <div class="services-block padding-45px-tb padding-25px-lr sm-padding-35px-tb sm-padding-20px-lr xs-padding-30px-tb xs-padding-15px-lr last-paragraph-no-margin">
                    <div class="title-box margin-25px-bottom sm-margin-15px-bottom">
                        <i class="fas fa-envelope text-theme-color"></i>
                        <div class="box-circle-large"></div>
                        <div class="box-circle-small"></div>
                    </div>
                    <div class="text-extra-dark-gray text-uppercase text-small font-weight-600 alt-font margin-5px-bottom">E-mail Us</div>
                    <p class="center-col"><a href="javascript:void(0)">group8@gmail.com</a>
                        <br><a href="javascript:void(0)">group8@cis.mak.ac.ug</a></p>
                </div>
            </div>
            <!-- end -->
        </div>

    </div>
</section>
<!-- end contact info section -->

<!-- start contact form -->
<section>
    <div class="container">
        <div class="row">
            <div class="col-12 wow fadeIn">

                <div class="section-heading">
                    <h3>Get in Touch</h3>
                    <p class="width-55 sm-width-75 xs-width-95">We are available 24/7 by e-mail and phone.</p>
                </div>

                <form method="post" action="bat/rd-mailform.php" class="mailform off2">
                    <input type="hidden" name="form-type" value="contact">
                    <div class="row">
                        <div class="col-md-4">
                            <input type="text" name="name" placeholder="Your Name:" data-constraints="@LettersOnly @NotEmpty">
                        </div>
                        <div class="col-md-4">
                            <input type="text" name="phone" placeholder="Telephone:" data-constraints="@Phone">
                        </div>
                        <div class="col-md-4">
                            <input type="text" name="email" placeholder="Email:" data-constraints="@Email @NotEmpty">
                        </div>
                        <div class="col-md-12">
                            <textarea name="message" rows="5" placeholder="Message:" data-constraints="@NotEmpty"></textarea>
                        </div>
                        <div class="mfControls col-md-12">
                            <button type="submit" class="butn">Sumbit comment</button>
                        </div>
                    </div>
                </form>

            </div>
        </div>
    </div>
</section>
<!-- end contact form -->

app/views/courses/index.html.erb
<%= provide(:title, 'Course Outline') %>
<!-- start page title section -->
<section class="page-title-section bg-img cover-background theme-overlay" data-overlay-dark="7" data-background="<%= image_tag("bg9.jpg") %>">
    <div class="container">

        <div class="row">
            <div class="col-md-12">
                <h1>Course Outline</h1>
            </div>
            <div class="col-md-12">
                <ul>
                    <li><a href="<%= root_path %>">Home</a></li>
                    <li><a href="javascript:void(0)">Course Outline</a></li>
                </ul>
            </div>
        </div>

    </div>
</section>
<!-- end page title section -->
<section class="bg-light-gray">
    <div class="container">
        <div class="text-center section-heading">
            <h2>Data Structures and Algorithms</h2>
        </div>
        <div class="row">
          <!--  start blog left-->
          <div class="col-lg-9 col-md-12 padding-50px-right sm-padding-15px-right sm-margin-50px-bottom">
              <div class=blog-list-simple>
                <% @courses.each_with_index do |course, i| %>
                  <div class="row">
                      <div class="col-md-12">
                          <div class="blog-list-simple-text"><span>Lecture <%=(i+1)%></span>
                              <h4><%=course.topic%></h4>
                              <ul class="meta">
                                  <li>
                                      <a href="javascript:void(0);">
                                          <i aria-hidden="true" class="fa fa-user"></i><%=course.lecturer_name%>
                                      </a>
                                  </li>
                                  <li>
                                      <a href="javascript:void(0);">
                                          <i aria-hidden="true" class="fas fa-calendar-alt"></i><%=course.created_at.to_datetime.strftime("%b %d, %Y %I:%M%P")%>
                                      </a>
                                  </li>
                              </ul>
                                  <div class="text-left margin-10px-top"><a href="<%= course_path(course) %>" class="butn small"><span>Course content</span></a></div>
                          </div>
                      </div>
                  </div>
                <% end %>
              </div>
              <!-- start pager  -->
            <!-- course pagination to be placed here -->
            <%= paginate @courses %>
              <!-- end pager -->
          </div>
          <!--  end blog left-->
        </div>
    </div>
</section>
<!-- end service section -->

app/views/courses/show.html.erb
<%= provide(:title, 'Courses') %>
<!-- start page title section -->
<section class="page-title-section bg-img cover-background theme-overlay" data-overlay-dark="7" data-background="img/banner/bg9.jpg">
    <div class="container">

        <div class="row">
            <div class="col-md-12">
                <h1>Course Content</h1>
            </div>
            <div class="col-md-12">
                <ul>
                    <li><a href="<%= course_outline_path %>">Course Outline</a></li>
                    <li><a href="javascript:void(0)">Course Content</a></li>
                </ul>
            </div>
        </div>

    </div>
</section>
<!-- end page title section -->
<section class="bg-light-gray">
    <div class="container">
        <div class="text-center section-heading">
            <h2><%= @course.topic %></h2>
        </div>
        <div class="row">
          <!--  start blog left-->
          <div class="col-lg-9 col-md-12 padding-50px-right sm-padding-15px-right sm-margin-50px-bottom">
              <div class=blog-list-simple>
                  <div class="row">
                      <div class="col-md-12">
                          <div class="blog-list-simple-text"><span><%= @course.topic%> Description</span>
                              <ul class="meta">
                                  <li>
                                      <a href="javascript:void(0);">
                                          <i aria-hidden="true" class="fa fa-user"></i><%= @course.lecturer_name%>
                                      </a>
                                  </li>
                                  <li>
                                      <a href="javascript:void(0);">
                                          <i aria-hidden="true" class="fas fa-calendar-alt"></i><%= @course.created_at.to_datetime.strftime("%b %d, %Y %I:%M%P")%>
                                      </a>
                                  </li>
                              </ul>
                                <p><%= @course.description %></p>
                                  <div class="text-left margin-10px-top"><a href="<%= course_outline_path %>" class="butn small"><span>Course Outline</span></a></div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <!--  end blog left-->
        </div>
    </div>
</section>
<!-- end service section -->

app/views/interactions/index.html.erb
<%= provide(:title,'STACKS')%>
<!-- start page title section -->
<section class="page-title-section bg-img cover-background theme-overlay" data-overlay-dark="7" data-background="<%= image_tag("bg9.jpg") %>">
    <div class="container">

        <div class="row">
            <div class="col-md-12">
                <h1>Console Interation</h1>
            </div>
            <div class="col-md-12">
                <ul>
                    <li><a href="<%= root_path %>">Home</a></li>
                    <li><a href="javascript:void(0)">Console Interation</a></li>
                </ul>
            </div>
        </div>
        <%= @console %>
    </div>
</section>
<!-- end page title section -->

app/views/sorting/index.html.erb
<%= provide(:title, 'Sorting') %>
<section>
    <div class="container" align="center">
      <h5>Sorting Algorithms</h5>
      <div class="row">
        <div class="col-lg-6 col-md-12 sm-margin-20px-bottom margin-twenty-five-left">
          <%= form_tag(sorted_path, :method => "post", remote: true) do %>
            <%= select_tag :sort_method, options_for_select(["Select option", "Bubble sort", "Insertion sort", "Selection sort", "Quick sort",
            "Merge sort"])%>
            <%= number_field_tag :number, params[:number], placeholder: "Enter number of elements needed", required: true %>
            <%= submit_tag "SORT",class: 'btn btn-primary', :name => nil %>
          <% end %>
        </div>
      </div>
    </div>
</section>

app/views/sorting/sorted.html.erb
<%= provide(:title, 'Sorting Results') %>
<section class="bg-light-gray">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 col-md-12 sm-margin-20px-bottom">
      <div class="services-block padding-45px-tb padding-25px-lr sm-padding-35px-tb sm-padding-20px-lr xs-padding-30px-tb xs-padding-15px-lr last-paragraph-no-margin wow fadeInUp">
        <div class="text-extra-dark-gray text-uppercase text-small font-weight-600 alt-font margin-5px-bottom">Unsorted Array</div>
        <p class="center-col">
          <% if @method == "Bubble sort"%>
            <p>Unsorted:</p>
            <p><%=@unsorted%></p>
          <% end %>
          <% if @method == "Insertion sort"%>
            <p>Unsorted:</p>
            <p><%=@unsorted%></p>
          <% end %>
          <% if @method == "Selection sort"%>
            <p>Unsorted:</p>
            <p><%=@unsorted%></p>
          <% end %>
          <% if @method == "Merge sort"%>
            <p>Unsorted:</p>
            <p><%=@unsorted%></p>
          <% end %>
          <% if @method == "Quick sort"%>
            <p>Unsorted:</p>
            <p><%=@unsorted%></p>
          <% end %>
        </p>
      </div>
      </div>
      <div class="col-lg-6 col-md-12 sm-margin-20px-bottom">
      <div class="services-block padding-45px-tb padding-25px-lr sm-padding-35px-tb sm-padding-20px-lr xs-padding-30px-tb xs-padding-15px-lr last-paragraph-no-margin wow fadeInUp">
        <div class="text-extra-dark-gray text-uppercase text-small font-weight-600 alt-font margin-5px-bottom">Result for <%=@method%></div>
        <p class="center-col">
          <% if @method == "Bubble sort"%>
            <p>Bubble sorted Array:</p>
            <p><%= @result%></p>
          <% end %>
          <% if @method == "Insertion sort"%>
            <p>Insertion sorted Array:</p>
            <p><%= @result%></p>
          <% end %>
          <% if @method == "Selection sort"%>
            <p>Selection sorted Array:</p>
            <p><%= @result%></p>
          <% end %>
          <% if @method == "Merge sort"%>
            <p>Merge sorted Array:</p>
            <p><%= @result%></p>
          <% end %>
          <% if @method == "Quick sort"%>
            <p>Quick sorted Array:</p>
            <p><%= @result%></p>
          <% end %>
        </p>
      </div>
      </div>
    </div>
  </div>
</section>