config/routes.rb
Rails.application.routes.draw do
  resources :courses
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'home#index'
  match '/course_outline' => "courses#index", via: ['get']
  match '/our_team' => "team#index", via: ['get']
  match '/interactions' => "interactions#index", via: ['get']
  match '/contact_us' => "contact#index", via: ['get']
  match '/fibonacci_and_factorial' => "computations#index", via: ['get']
  match '/fibonacci_and_factorial_computation' => "computations#fibonacci_and_factorial", via: ['post']
  match '/tower_of_hanoi' => "computations#index_hanoi", via: ['get']
  match '/tower_of_hanoi_computation' => "computations#tower_of_hanoi", via: ['post']
  match '/sorting' => "sorting#index", via: ['get']
  match '/sorted' => "sorting#sorted", via: ['post']
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  paginates_per 5
end

app/controllers/about_controller.rb
class AboutController < ApplicationController

  def index
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/computations_controller.rb
class ComputationsController < ApplicationController
  skip_before_action :verify_authenticity_token
  include Computations

  def index
  end

  def index_hanoi
  end

  def fibonacci_and_factorial
    #method to execute the fibonacci  and factorial functions
    @method = params[:method]
    @number = (params[:number]).to_i
    if @method == "Fibonacci"
      @result = fibonacci_computation(@number)
    end
    if @method == "Factorial"
      @result = factorial_computation(@number)
    end
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

  def index
  end
  
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show]

  def index
    @courses = Course.all.page params[:page]
  end

  def show
  end

  private
  def set_course
    @course = Course.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
end

app/controllers/sorting_controller.rb
class SortingController < ApplicationController
  skip_before_action :verify_authenticity_token
  include Computations
  def index
  end

  def sorted
    @arr = []
    @unsorted = []
    @method = params[:sort_method]
    number = (params[:number]).to_i
    for i in 1..number
      i = rand(1000)
      @arr << i
      @unsorted << i
    end
    if @method == "Bubble sort"
      @result = bubble_sort(@arr)
    elsif @method == "Insertion sort"
      @result = insertion_sort(@arr)
    elsif @method == "Selection sort"
      @result = selection_sort(@arr)
    elsif @method == "Quick sort"
      @result = quick_sort(@arr)
    elsif @method == "Merge sort"
      @result = merge_sort(@arr)
    else
      @arr = []
      @unsorted = []
    end
  end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController

  def index
  end
  
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/computations_helper.rb
module ComputationsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/interactions_helper.rb
module InteractionsHelper
end

app/helpers/sorting_helper.rb
module SortingHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/views/layouts/_meta_tags.html.erb
<meta name="description" content="Send Bulk SMS messages to Uganda, Kenya ,Tanzania and Democratic Republic of Congo. Use the most advanced web interface and a very fast REST API to send SMS. We are Africa's best SMS provider. ">
<meta charset="UTF-8">
<meta name="keywords" content="Bulk SMS,Bulk SMS Uganda, Bulk SMS Kenya, Bulk SMS Tanzania, Bulk SMS Democratic Republic of Congo, SMS API, Send Bulk SMS, REST API, SMS Gateway, SMS Provider, SMS reseller">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
   <head>
      <!-- metas -->
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
      <!-- title  -->
      <title>Data Structures | <%= yield(:title) %></title>
      <!-- favicon -->
      <link rel="shortcut icon" href="img/logos/favicon.png" />
      <link rel="apple-touch-icon" href="img/logos/apple-touch-icon-57x57.png" />
      <link rel="apple-touch-icon" sizes="72x72" href="img/logos/apple-touch-icon-72x72.png" />
      <link rel="apple-touch-icon" sizes="114x114" href="img/logos/apple-touch-icon-114x114.png" />
      <!-- precompile all crystal css -->
      <%= stylesheet_link_tag  "application", :media => "all" %>
   </head>

   <body>
     <!-- start page loading -->
     <div id="preloader">
         <div class="row loader">
             <div class="loader-icon"></div>
         </div>
     </div>
     <!-- end page loading -->
     <!-- start main-wrapper section -->
      <div class="main-wrapper">
        <!-- start header section -->
        <%= render "layouts/partials/header" %>
        <!-- end header section -->
        <%= yield %>
        <!-- start footer section -->
        <%= render 'layouts/partials/footer'unless current_page?(interactions_path) %>
        <!-- end footer section -->
        <!-- start scroll to top -->
        <a href="javascript:void(0)" class="scroll-to-top"><i class="fas fa-angle-up" aria-hidden="true"></i></a>
        <!-- end scroll to top -->
        <!-- compile all js -->
        <%= javascript_include_tag 'application' %>
      </div>
      <!-- end main-wrapper section -->
   </body>
</html>

app/views/layouts/partials/_footer.html.erb
<footer>
    <div class="container">
        <div class="row margin-30px-bottom padding-30px-bottom border-bottom border-color-light-white">
            <div class="col-lg-4 col-md-12 sm-margin-30px-bottom text-center">
                <h3 class="footer-title-style text-white">Phone</h3>
                <p class="font-size16 sm-font-size14">(+256) 779467316</p>
            </div>

            <div class="col-lg-4 col-md-12 sm-margin-30px-bottom text-center">
                <h3 class="footer-title-style text-white">Email</h3>
                <p class="font-size16 sm-font-size14">group8@gmail.com</p>
            </div>

            <div class="col-lg-4 col-md-12 text-center">
                <h3 class="footer-title-style text-white">Location</h3>
                <p class="font-size16 sm-font-size14"> Makerere University, COCIS.</p>
            </div>
        </div>

        <div class="row">
            <div class="col-12 text-center">
                <ul class="social-icon-style2 no-margin">
                    <li>
                        <a href="javascript:void(0)"><i class="fab fa-facebook-f"></i></a>
                    </li>
                    <li>
                        <a href="javascript:void(0)"><i class="fab fa-twitter"></i></a>
                    </li>
                    <li>
                        <a href="javascript:void(0)"><i class="fab fa-google-plus-g"></i></a>
                    </li>
                    <li>
                        <a href="javascript:void(0)"><i class="fab fa-linkedin-in"></i></a>
                    </li>
                </ul>
            </div>
        </div>

    </div>
    <div class="footer-bar xs-font-size13">
       <div class="container">
          <div class="row">
             <div class="col-md-6 text-left xs-text-center xs-margin-5px-bottom">
                <p>&copy; Copyright Group Number 2019. All Rights Reserved.</p>
             </div>
             <div class="col-md-6 text-right xs-text-center">
                Design and Developed by: Group 8
             </div>
          </div>
       </div>
    </div>
</footer>
<!-- end footer section -->

app/views/layouts/partials/_header.html.erb
<!-- start header section -->
<header>
    <div class="navbar-default">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-12 col-lg-12">
                    <div class="menu_area alt-font">
                        <nav class="navbar navbar-expand-lg navbar-light no-padding">

                            <div class="navbar-header navbar-header-custom">
                                <!-- start logo -->
                                <!-- <a href="#" class="navbar-brand"><#%=image_tag("logo.png", :id => "logo")%></a> -->
                                <a href="#" class="navbar-brand" style="color: skyblue">Group 8</a>
                                <!-- end logo -->
                            </div>

                            <div class="navbar-toggler"></div>

                            <!-- start menu Area -->
                            <ul class="navbar-nav ml-auto" id="nav" style="display: none;">
                                <li><a href="<%= root_path %>">Home</a></li>
                                <li><a href="<%= course_outline_path %>">Course</a></li>
                                <li><a href="<%= our_team_path %>">Our Team</a></li>
                                <li><a href="<%= contact_us_path %>">Contact Us</a></li>
                                <li><a href="<%= interactions_path %>">Stacks</a></li>
                                <li><a href="javascript:void(0)">Computations</a>
                                    <ul>
                                        <li><a href="<%= fibonacci_and_factorial_path %>">Fibonacci & Factorial</a></li>
                                        <li><a href="<%= tower_of_hanoi_path %>">Tower of Hanoi</a></li>
                                        <li><a href="<%= sorting_path %>">Sorting</a></li>
                                    </ul>
                                </li>
                            </ul>
                            <!-- end menu Area -->

                            <!-- start attribute navigation -->
                            <div class="attr-nav sm-no-margin sm-margin-65px-right">
                                <ul>
                                    <li class="search"><a href="javascript:void(0)"><i class="fa fa-search"></i></a></li>
                                </ul>
                            </div>
                            <!-- end attribute navigation -->

                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- end header section -->